env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-undef:
    - off
  no-unused-vars:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - off
    - never
ignorePatterns:
  - lib
  - src/assets/javascripts
