version: '2.1'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c 'set -ex && /app/bin/xpaste db create && /app/bin/xpaste db migrate && /app/bin/xpaste'
    ports:
      - "3000:3000"
    environment:
      AMBER_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: x_paste_test
      HOST: 0.0.0.0
      PROCESS_COUNT: 1
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget -qO- http://localhost:3000/metrics
      interval: 1s
      timeout: 1s
      retries: 30

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: x_paste_test
    command: -c fsync=off -c full_page_writes=off
    healthcheck:
      test: ["CMD", "pg_isready" , "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 60
    logging:
      driver: none

  test_suite:
    build:
      context: ./
      dockerfile: Dockerfile.cypress
    depends_on:
      app:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://app:3000
    command: npx cypress run --headless -b chrome
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json