secret_key_base: mZl3HqpieaqtlVWDY9BKC_b9hjafj31W3UJr97HqORk
port: 3000
name: xpaste

host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:@localhost:5432/xpaste_test
auto_reload: false

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
