---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  dnsNames:
  - {{ .Values.ingress.host }}
  - www.{{ .Values.ingress.host }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Release.Name }}-tls
...
