---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: app
  name: {{ .Release.Name }}
spec:
{{ if .Values.review.enabled }}
  minAvailable: 0
{{ else }}
  minAvailable: 1
{{ end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: app
...
